apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - argocd.yaml
  - managedclustersetbinding.yaml
  - argocd-ssh-known-hosts-cm.yaml
  - argocd-tls-certs-cm.yaml
  - ztp-repo.yaml

# Sync-wave annotations control the order of resource creation in ArgoCD:
# - namespace.yaml has sync-wave: "-55" (creates first)
# - argocd.yaml has sync-wave: "-54" (creates second)
# - argocd-ssh-known-hosts-cm.yaml has sync-wave: "-40" (creates third)
# - argocd-tls-certs-cm.yaml has sync-wave: "-40" (creates third)
# - ztp-repo.yaml has sync-wave: "-40" (creates third)
# - managedclustersetbinding.yaml has sync-wave: "-25" (creates fourth)
# This ensures the namespace exists before the ArgoCD instance is created,
# and the ArgoCD configuration resources are created before the managed cluster set binding
