apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - argocd.yaml
  - managedclustersetbinding.yaml

# Sync-wave annotations control the order of resource creation in ArgoCD:
# - namespace.yaml has sync-wave: "-55" (creates first)
# - argocd.yaml has sync-wave: "-54" (creates second)
# - managedclustersetbinding.yaml has sync-wave: "-25" (creates third)
# This ensures the namespace exists before the ArgoCD instance is created

patches:
  # Patch for namespace - ensure proper name
  - target:
      kind: Namespace
      name: telco-hub-pattern
    patch: |-
      - op: replace
        path: /metadata/name
        value: telco-hub-pattern
