---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: ztp-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
# Configuration examples:
# For SSH repo access, configure: url, insecure, sshPrivateKey (as shown below)
# For HTTPS repo access, configure: url, insecure, password, username, forceHttpBasicAuth
# More examples: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-repositories-yaml/
stringData:
  insecure: "false"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    INSERT PRIVATE KEY
    -----END OPENSSH PRIVATE KEY-----
  url: git@gitlab.example.com:namespace/repo.git
