---
# =============================================================================
# Telco Hub Pattern - Pattern Overrides
# =============================================================================
# This file contains environment-specific overrides for the telco-hub pattern.
# Update the values below to match your specific environment and requirements.

# =============================================================================
# PATTERN OVERRIDES
# =============================================================================

telcoHub:
  # -----------------------------------------------------------------------------
  # Git Repository Settings
  # -----------------------------------------------------------------------------
  # IMPORTANT: If disconnected, update these values for your environment!
  git:
    repoURL: https://github.com/openshift-kni/telco-reference.git
    targetRevision: main

  # -----------------------------------------------------------------------------
  # Component Selection
  # -----------------------------------------------------------------------------
  # Enable/disable telco-hub components as needed for your environment

  components:
    # Required Components (for basic telco-hub functionality)
    acm:
      enabled: true               # Advanced Cluster Management
    gitops:
      enabled: true               # GitOps operators and ArgoCD configuration
    talm:
      enabled: true               # Topology Aware Lifecycle Manager

    # ZTP Workflow (enable for cluster installation management)
    ztpInstallation:
      enabled: false              # GitOps ZTP cluster installation workflow

    # Optional Components (enable as needed for your use case)
    lso:
      enabled: false              # Local Storage Operator
    odf:
      enabled: false              # OpenShift Data Foundation
    backupRecovery:
      enabled: false              # Backup and Recovery (Velero/OADP)
    logging:
      enabled: false              # Cluster Logging Operator

  # =============================================================================
  # CUSTOMIZATION OVERLAYS
  # =============================================================================
  # Use kustomize patches to customize the deployed resources for your environment.
  # These patches modify the base reference-crs to match your specific requirements.

  # -----------------------------------------------------------------------------
  # GitOps Operator Customization
  # -----------------------------------------------------------------------------
  argocd:
    kustomizePatches:
      # Customize the hub-config Application to point to your telco-hub configuration
      - target:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: hub-config
        patch: |-
          - op: replace
            path: "/spec/source"
            value:
              path: "telco-hub/"
              repoURL: "http://jumphost.inbound.lab:3000/kni/telco-reference.git"
              targetRevision: "add-telco-hub-pattern-bos2"

      # Ensure the GitOps operator uses Red Hat catalog and proper configuration
      - target:
          group: operators.coreos.com
          version: v1alpha1
          kind: Subscription
          name: openshift-gitops-operator
        patch: |-
          - op: replace
            path: "/metadata/namespace"
            value: "openshift-operators"
          - op: replace
            path: "/spec/source"
            value: "redhat-operators"

      # Ensure the GitOps operator has the same resource configuration as validated patterns
      - target:
          group: operators.coreos.com
          version: v1alpha1
          kind: OperatorGroup
          name: openshift-gitops-operator
          namespace: openshift-gitops-operator
        patch: |-
          - op: replace
            path: "/metadata/name"
            value: "openshift-gitops-operator-group"
          - op: replace
            path: "/metadata/namespace"
            value: "openshift-gitops"
          - op: replace
            path: "/spec/targetNamespaces"
            value:
              - "openshift-gitops"

  # -----------------------------------------------------------------------------
  # ACM (Advanced Cluster Management) Customization
  # -----------------------------------------------------------------------------
  acm:
    kustomizePatches:
      # Configure ACM Subscription to match the desired configuration
      - target:
          group: operators.coreos.com
          version: v1alpha1
          kind: Subscription
          name: open-cluster-management-subscription
        patch: |-
          - op: replace
            path: "/spec/source"
            value: "redhat-operators"

      # Configure ACM OperatorGroup name and upgrade strategy
      - target:
          group: operators.coreos.com
          version: v1
          kind: OperatorGroup
          name: open-cluster-management-group
        patch: |-
          - op: add
            path: "/spec/upgradeStrategy"
            value: "Default"

      # Configure ACM MultiClusterEngine to match the desired configuration
      - target:
          group: multicluster.openshift.io
          version: v1
          kind: MultiClusterEngine
          name: multiclusterengine
        patch: |-
          - op: replace
            path: "/spec/overrides/components"
            value:
            - configOverrides: {}
              enabled: true
              name: local-cluster
            - configOverrides: {}
              enabled: true
              name: assisted-service
            - configOverrides: {}
              enabled: true
              name: cluster-lifecycle
            - configOverrides: {}
              enabled: true
              name: cluster-manager
            - configOverrides: {}
              enabled: true
              name: discovery
            - configOverrides: {}
              enabled: true
              name: hive
            - configOverrides: {}
              enabled: true
              name: server-foundation
            - configOverrides: {}
              enabled: true
              name: cluster-proxy-addon
            - configOverrides: {}
              enabled: true
              name: hypershift-local-hosting
            - configOverrides: {}
              enabled: true
              name: console-mce
            - configOverrides: {}
              enabled: true
              name: hypershift
            - configOverrides: {}
              enabled: false
              name: managedserviceaccount
            - configOverrides: {}
              enabled: false
              name: image-based-install-operator
            - configOverrides: {}
              enabled: false
              name: cluster-api-preview
            - configOverrides: {}
              enabled: false
              name: cluster-api-provider-aws-preview

  # -----------------------------------------------------------------------------
  # TALM Operator Customization
  # -----------------------------------------------------------------------------
  talm:
    kustomizePatches:
      # Ensure the TALM operator uses Red Hat catalog
      - target:
          group: operators.coreos.com
          version: v1alpha1
          kind: Subscription
          name: openshift-topology-aware-lifecycle-manager-subscription
        patch: |-
          - op: replace
            path: "/spec/source"
            value: "redhat-operators"

  # -----------------------------------------------------------------------------
  # ZTP Workflow Customization
  # -----------------------------------------------------------------------------
  # Configure ZTP Applications to point to your cluster and policy repositories
  ztpInstallation:
    kustomizePatches:
      # Configure clusters Application
      - target:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: clusters
        patch: |-
          - op: replace
            path: "/spec/source/path"
            value: "clusters"
          - op: replace
            path: "/spec/source/repoURL"
            value: "http://jumphost.inbound.lab:3000/kni/faredge-ztp.git"
          - op: remove
            path: "/spec/syncPolicy"

      # Configure policies Application
      - target:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: policies
        patch: |-
          - op: replace
            path: "/spec/source/path"
            value: "site-policies"
          - op: replace
            path: "/spec/source/repoURL"
            value: "http://jumphost.inbound.lab:3000/kni/faredge-ztp.git"

  # -----------------------------------------------------------------------------
  # Local Storage Operator Customization
  # -----------------------------------------------------------------------------
  lso:
    kustomizePatches:
      # Ensure the LSO operator uses Red Hat catalog
      - target:
          group: operators.coreos.com
          version: v1alpha1
          kind: Subscription
          name: local-storage-operator
        patch: |-
          - op: replace
            path: "/spec/source"
            value: "redhat-operators"

  # -----------------------------------------------------------------------------
  # ODF (OpenShift Data Foundation) Customization
  # -----------------------------------------------------------------------------
  odf:
    kustomizePatches:
      # Ensure the ODF operator uses Red Hat catalog
      - target:
          group: operators.coreos.com
          version: v1alpha1
          kind: Subscription
          name: odf-operator
        patch: |-
          - op: replace
            path: "/spec/source"
            value: "redhat-operators"

      # Configure the StorageCluster for LVMS with 100Gi storage
      - target:
          group: ocs.openshift.io
          version: v1
          kind: StorageCluster
          name: ocs-storagecluster
        patch: |-
          - op: replace
            path: "/spec/storageDeviceSets/0/dataPVCTemplate/spec/resources/requests/storage"
            value: "100Gi"
          - op: replace
            path: "/spec/storageDeviceSets/0/dataPVCTemplate/spec/storageClassName"
            value: "lvms-vg1"

  # -----------------------------------------------------------------------------
  # Cluster Logging Operator Customization
  # -----------------------------------------------------------------------------
  logging:
    kustomizePatches:
      # Ensure the Cluster Logging operator uses Red Hat catalog and stable-6.3 channel
      - target:
          group: operators.coreos.com
          version: v1alpha1
          kind: Subscription
          name: cluster-logging
        patch: |-
          - op: replace
            path: "/spec/source"
            value: "redhat-operators"

      # Configure ClusterLogForwarder for hub-specific configuration
      - target:
          group: observability.openshift.io
          version: v1
          kind: ClusterLogForwarder
          name: instance
        patch: |-
          - op: replace
            path: "/spec/outputs/0/kafka/url"
            value: "tcp://jumphost.inbound.lab:9092/logs"
          - op: add
            path: /spec/filters/0/openshiftLabels
            value:
              cluster-role: hub
              environment: production
              telco-component: hub

# =============================================================================
# QUICK CONFIGURATION REFERENCE
# =============================================================================
# To customize this configuration:
#
# 1. Update git.repoURL and git.targetRevision to point to your telco-reference repo
# 2. Enable/disable components based on your requirements
# 3. Modify kustomize patches to match your environment-specific values
# 4. Update ZTP repoURL values in ztpInstallation patches for your cluster/policy repos
# 5. Ensure all repoURL values point to accessible Git repositories
#
# Common customizations:
# - Change operator catalog sources (community-operators vs. redhat-operators)
# - Modify ZTP repository URLs and paths for clusters and policies
# - Adjust Application source paths and target revisions
