---
# =============================================================================
# Telco Hub Pattern - Global Values
# =============================================================================
# This file contains global configuration values that apply across all clusters
# and environments in the telco-hub pattern. These values define the overall
# pattern behavior and should be consistent across all deployments.
#
# =============================================================================
# GLOBAL PATTERN CONFIGURATION
# =============================================================================

global:
  pattern: telco-hub-pattern              # Name of the validated pattern

  # Global pattern options that affect all clusters
  options:
    useCSV: false                         # Whether to use specific ClusterServiceVersions for operators
    syncPolicy: Automatic                 # Default ArgoCD sync policy (Automatic/Manual)
    installPlanApproval: Automatic        # Default operator install plan approval (Automatic/Manual)

# =============================================================================
# MAIN CLUSTER CONFIGURATION
# =============================================================================
# Configuration for the main (hub) cluster that manages the telco pattern

main:
  clusterGroupName: hub                             # Name of the main cluster group

  # Multi-source Helm chart configuration
  multiSourceConfig:
    enabled: true                                   # Enable multi-source configuration for complex charts
    clusterGroupChartVersion: "0.9.*"               # Version constraint for clusterGroup charts

  gitops:
    channel: "gitops-1.16"                          # OpenShift GitOps operator channel version
