---
# =============================================================================
# Telco Hub Pattern - Hub Cluster Configuration
# =============================================================================
# This file defines the hub cluster configuration for the telco-hub pattern.
# The hub cluster serves as the central management point for the entire telco
# infrastructure, providing GitOps, cluster management, and policy enforcement.
#
# =============================================================================
# HUB CLUSTER GROUP CONFIGURATION
# =============================================================================

clusterGroup:
  # Cluster identification and role
  name: hub                               # Name of this cluster group
  isHubCluster: true                      # Designates this as the hub/management cluster

  # Management of below resource is delegated to the telco-hub kustomization app
  # in order to prevent systematic conflicts between the Pattern operator and
  # the Telco Hub Reference Design Specifications.
  namespaces: []
  subscriptions: {}
  projects: {}

  # =============================================================================
  # TELCO HUB APPLICATION
  # =============================================================================
  applications:

    telco-hub:
      name: hub-config
      kustomize: true                          # Use Kustomize for manifest processing
      path: kustomize/overlays/telco-hub

      # ArgoCD synchronization behavior configuration
      syncPolicy:
        automated:
          prune: true                          # Remove resources not in Git
        retry:
          limit: 6                             # Maximum number of sync retries (adjusted for ~20m total)
          backoff:
            duration: 15s                      # Initial retry delay
            factor: 2                          # Backoff multiplier
            maxDuration: 15m                   # Maximum retry delay (increased to 15m)
