---
global:
  pattern: telco-hub-pattern

telcoHub:
  git:
    repoURL: "https://github.com/openshift-kni/telco-reference.git"
    targetRevision: "main"
  
  # Component enablement
  components:
    logging:
      enabled: true
  
  logging:
    # Optional kustomize patches for logging configuration
    kustomizePatches:
    # Example patch structure:
      # Ensure the Cluster Logging operator uses Red Hat catalog and stable-6.3 channel
      - target:
          group: operators.coreos.com
          version: v1alpha1
          kind: Subscription
          name: cluster-logging
        patch: |-
          - op: replace
            path: "/spec/source"
            value: "redhat-operators"
          - op: replace
            path: "/spec/channel"
            value: "stable-6.3"

      # Configure ClusterLogForwarder for hub-specific configuration
      - target:
          group: observability.openshift.io
          version: v1
          kind: ClusterLogForwarder
          name: instance
        patch: |-
          - op: replace
            path: "/spec/outputs/0/kafka/url"
            value: "tcp://jumphost.inbound.lab:9092/logs"
          - op: add
            path: /spec/filters/0/openshiftLabels
            value:
              cluster-role: hub
              environment: production
              telco-component: hub
  
  argocd:
    syncPolicy:
      automated:
        allowEmpty: true
        prune: true
        selfHeal: true
      retry:
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 10m 
