# ImageSetConfiguration for Telco Hub Pattern
#
# This file references the authoritative ImageSetConfiguration from the
# telco-reference repository to ensure consistency and reduce maintenance overhead.
#
# For the latest configuration, refer to:
# https://github.com/openshift-kni/telco-reference/tree/main/telco-hub/install/mirror-registry
#
# Note: Users may select a different release branch based on their target OpenShift Hub deployment version.
#
# To use this configuration:
# 1. Download the ImageSetConfiguration from the telco-reference repository
# 2. Place it in this directory
# 3. Update the path references in your deployment scripts
#
# This approach ensures the pattern always uses the latest validated
# operator versions and configurations from the official telco-reference design.

# =============================================================================
#
# The VP (Validated Patterns) framework requires additional components beyond the base
# telco-reference configuration, including the patterns-operator and specific operator
# versions that have been validated by QE for telco hub deployments.

# ---
# kind: ImageSetConfiguration
# apiVersion: mirror.openshift.io/v2alpha1
# mirror:
#   ... REDACTED ...
#
#   operators:
#   - catalog: registry.redhat.io/redhat/community-operator-index:<catalog-version>
#     targetCatalog: openshift-marketplace/community-operators-disconnected
#     packages:
#       - name: patterns-operator
#   ... REDACTED ...
#
#   - name: openshift-gitops-operator
#     defaultChannel: gitops-1.17          # <- ensure this is the same as the one in the values-global.yaml file
#     channels:
#     - name: gitops-1.17                  # <- ensure this is the same as the one in the values-global.yaml file
#   ... REDACTED ...
#
#
#   additionalImages:
#   - name: registry.redhat.io/ubi9/ubi-minimal:latest
#   - name: quay.io/hybridcloudpatterns/imperative-container:v1
#   ... REDACTED ...
#
#   helm: {}
