---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-proxy-config
  namespace: openshift-config
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGcjCCBFqgAwIBAgIFICIE...
    -----END CERTIFICATE-----
