---
# The tunings in this ArgoCD instance are aligned with the
# reference: https://github.com/openshift-kni/telco-reference/blob/main/telco-hub/configuration/reference-crs/required/gitops/addPluginsPolicy.yaml
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-54"
  name: telco-hub-gitops
  namespace: telco-hub-pattern
spec:
  applicationSet:
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  controller:
    processors: {}
    resources:
      limits:
        cpu: "16"
        memory: 32Gi
      requests:
        cpu: "1"
        memory: 2Gi
    sharding: {}
  grafana:
    enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
    route:
      enabled: false
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  initialSSHKnownHosts: {}
  kustomizeBuildOptions: --enable-alpha-plugins
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac:
    defaultPolicy: ""
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
    scopes: '[groups]'
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    env:
      - name: ARGOCD_EXEC_TIMEOUT
        value: 360s
      - name: KUSTOMIZE_PLUGIN_HOME
        value: /.config/kustomize/plugin
    initContainers:
      - args:
          - /.config
        command:
          - /exportkustomize.sh
        image: registry.redhat.io/openshift4/ztp-site-generate-rhel8:v4.19
        imagePullPolicy: Always
        name: kustomize-plugin
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /.config
            name: kustomize
      - args:
          - -c
          - mkdir -p /.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator
            && cp /policy-generator/PolicyGenerator-not-fips-compliant
            /.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator
        command:
          - /bin/bash
        image: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:v2.13
        imagePullPolicy: Always
        name: policy-generator-install
        volumeMounts:
          - mountPath: /.config
            name: kustomize
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
      requests:
        cpu: "1"
        memory: 2Gi
    volumeMounts:
      - mountPath: /.config
        name: kustomize
    volumes:
      - emptyDir: {}
        name: kustomize
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    route:
      enabled: true
    service:
      type: ""
