---
# =============================================================================
# Telco Hub Pattern - Disconnected Environment Prerequisites
# =============================================================================
# REQUIRED: Apply as Day-0 prerequisite before `pattern.sh make install`.
#
# Usage:
# 1. oc apply -k kustomize/air-gapped/prerequisites/
# 2. Deploy telco-hub pattern via `pattern.sh make install`
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-proxy/
  - operator-catalogs/

patches:

  # Add CA certificate bundle for self-signed GIT repositories in disconnected environments.
  # Required when the telco-hub pattern repo is hosted on local GIT servers with self-signed certificates
  # and without GIT authentication available. The pattern operator lack the ability of accepting
  # custom CAs currently, causing TLS verification failures during repo cloning.
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: cluster-proxy-config
      namespace: openshift-config
    patch: |-
      - op: add
        path: /data/ca-bundle.crt
        value: |
          -----BEGIN CERTIFICATE-----
          MIIGcjCCBFqgAwIBAgIFICIE...
          -----END CERTIFICATE-----

  # Pin RedHat operators catalog to index mirrored in local registry
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: CatalogSource
      name: redhat-operators-disconnected
    patch: |-
      - op: replace
        path: /spec/image
        value: <registry.example.com:8443>/openshift-marketplace/redhat-operators-disconnected:<version>

  # Pin Community operators catalog to index mirrored in local registry
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: CatalogSource
      name: community-operators-disconnected
    patch: |-
      - op: replace
        path: /spec/image
        value: <registry.example.com:8443>/openshift-marketplace/community-operators-disconnected:<version>
