---
name: Super linter

on: [push, pull_request]

jobs:
  build:
    # Name the Job
    name: Super linter
    # Set the agent to run on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@5126516654c75f76bca1de45dd82a3006d8890f9 # v5
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          persist-credentials: false

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@ffde3b2b33b745cb612d787f669ef9442b1339a6 # v8.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: '.*\.vscode/.*'
          VALIDATE_ANSIBLE: false
          VALIDATE_BASH: false
          VALIDATE_CHECKOV: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_YAML: false
          VALIDATE_YAML_PRETTIER: false
          # VALIDATE_KUBERNETES_KUBECONFORM: false
          # VALIDATE_NATURAL_LANGUAGE: false
          # VALIDATE_TEKTON: false
