# This is a job to be run in the validatedpatterns organization only.
# It tries to keep the rhdp-deploy branch uptodate by creating a PR from main
---
name: Sync main to rhdp-deploy
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    if: |
      github.repository_owner == 'validatedpatterns'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    name: Git Sync branch
    steps:
      - name: Checkout
        uses: actions/checkout@5126516654c75f76bca1de45dd82a3006d8890f9 # v5
        with:
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Opening pull request
        id: pull
        uses: mbaldessari/git-sync-branch@94bbe1d5b39e9e9b27c43b9a1bab8e5705c6b088 # v0.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "main"
          TO_BRANCH: "rhdp-deploy"
